---
kind: pipeline
type: docker
name: testing-pipeline-rehan

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  image: hello-world
  commands:
  - echo hello world

trigger:
  branch:
  - second_docker_file

