---
kind: pipeline
type: docker
name: testing-pipeline-rehan

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  image: node
  commands:
  - npm install

trigger:
  branch:
  - second_docker_file

